#konstanty jsou v souboru .env, případně .env.local ....
services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:80"
    volumes:
      #root webu
      - .:/var/www/html
      #konfigurace apache
      - .apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      #php.ini
      - .apache/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    #environment:
    #  PMA_HOST: db
    ports:
      #port phpmyadmin
      - "${PHP_MYADMIN_PORT}:80"
    depends_on:
      #závislost na db kontejneru
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      #pokud by měla být data persistentní
      #- ./db_data:/var/lib/mysql
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "${MYSQL_PORT}:3306"

